version: 2

jobs:
    build:
        docker:
            - image: hoishin/texlive:18.04
        steps:
            - run:
                name: Install required TeX packages
                command: |
                    tlmgr init-usertree
                    tlmgr install enumitem appendix tcolorbox pgf environ trimspaces nag
            - checkout
            - run: make build
            - persist_to_workspace:
                root: '.'
                paths:
                    - main.pdf
    deploy:
        machine:
            enabled: true
        steps:
            - attach_workspace:
                at: '.'
            - run: scp main.pdf ${DEPLOY_DEST}

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - master
